# Generated by Django 5.1.4 on 2026-06-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='المعرّف (slug)')),
                ('section', models.CharField(choices=[('workshops', 'الورش التدريبية'), ('center', 'أخبار المراكز'), ('events', 'الفعاليات'), ('articles', 'التوعية الأسرية')], max_length=20, verbose_name='القسم')),
                ('featured', models.BooleanField(default=False, verbose_name='مميّز')),
                ('title_ar', models.CharField(max_length=300, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='العنوان (إنجليزي)')),
                ('desc_ar', models.TextField(verbose_name='الوصف (عربي)')),
                ('desc_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('category_ar', models.CharField(blank=True, max_length=80, verbose_name='التصنيف (عربي)')),
                ('category_en', models.CharField(blank=True, max_length=80, verbose_name='التصنيف (إنجليزي)')),
                ('date_ar', models.CharField(blank=True, max_length=60, verbose_name='التاريخ (عربي)')),
                ('date_en', models.CharField(blank=True, max_length=60, verbose_name='التاريخ (إنجليزي)')),
                ('image', models.CharField(blank=True, max_length=300, verbose_name='مسار الصورة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('published', models.BooleanField(default=True, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خبر / مقال',
                'verbose_name_plural': 'الأخبار والفعاليات والمقالات',
                'ordering': ['section', 'order', '-created_at'],
            },
        ),
    ]
