# Generated by Django 5.1.4 on 2026-06-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_assessmentcard_branch_clinicalservice_featureitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'الرئيسية'), ('success', 'قصص النجاح'), ('specialists', 'الأخصائيون'), ('assessment', 'التقييم'), ('branches', 'الفروع'), ('careers', 'الوظائف'), ('news', 'الأخبار')], max_length=40, verbose_name='الصفحة')),
                ('block', models.CharField(help_text='مثال: stats, features, steps, cards', max_length=40, verbose_name='القسم')),
                ('key', models.SlugField(blank=True, max_length=160, verbose_name='المعرّف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('published', models.BooleanField(default=True, verbose_name='منشور')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='الأيقونة')),
                ('value', models.CharField(blank=True, max_length=60, verbose_name='القيمة/الرقم')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='اللون')),
                ('title_ar', models.CharField(blank=True, max_length=400, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=400, verbose_name='العنوان (إنجليزي)')),
                ('text_ar', models.TextField(blank=True, verbose_name='النص (عربي)')),
                ('text_en', models.TextField(blank=True, verbose_name='النص (إنجليزي)')),
                ('data_ar', models.JSONField(blank=True, default=list, verbose_name='بيانات إضافية (عربي)')),
                ('data_en', models.JSONField(blank=True, default=list, verbose_name='بيانات إضافية (إنجليزي)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عنصر قسم',
                'verbose_name_plural': 'عناصر أقسام الصفحات',
                'ordering': ['page', 'block', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(choices=[('programs', 'برامج تأهيلية'), ('clinical', 'خدمات عيادية'), ('techniques', 'تقنيات تأهيلية')], max_length=20, verbose_name='التبويب')),
                ('slug', models.SlugField(blank=True, max_length=140, verbose_name='المعرّف (slug)')),
                ('href', models.CharField(blank=True, max_length=200, verbose_name='رابط مخصّص')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('published', models.BooleanField(default=True, verbose_name='منشور')),
                ('badge_ar', models.CharField(blank=True, max_length=120, verbose_name='الشارة (عربي)')),
                ('badge_en', models.CharField(blank=True, max_length=120, verbose_name='الشارة (إنجليزي)')),
                ('title_ar', models.CharField(max_length=300, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='العنوان (إنجليزي)')),
                ('desc_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('desc_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('suits_ar', models.CharField(blank=True, max_length=300, verbose_name='يناسب (عربي)')),
                ('suits_en', models.CharField(blank=True, max_length=300, verbose_name='يناسب (إنجليزي)')),
                ('age_ar', models.CharField(blank=True, max_length=120, verbose_name='الفئة العمرية (عربي)')),
                ('age_en', models.CharField(blank=True, max_length=120, verbose_name='الفئة العمرية (إنجليزي)')),
                ('features_ar', models.JSONField(blank=True, default=list, verbose_name='المميزات (عربي)')),
                ('features_en', models.JSONField(blank=True, default=list, verbose_name='المميزات (إنجليزي)')),
                ('regions_ar', models.JSONField(blank=True, default=list, verbose_name='المناطق (عربي)')),
                ('regions_en', models.JSONField(blank=True, default=list, verbose_name='المناطق (إنجليزي)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بطاقة خدمة',
                'verbose_name_plural': 'بطاقات الخدمات (الفهرس)',
                'ordering': ['tab', 'order', 'id'],
            },
        ),
    ]
