# Generated by Django 5.1.4 on 2026-06-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_sectionitem_servicecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='اللوجو')),
                ('logo_path', models.CharField(blank=True, default='/figma/imgImage.png', help_text='يُستخدم لو لم تُرفع صورة لوجو', max_length=300, verbose_name='مسار اللوجو (احتياطي)')),
                ('site_name_ar', models.CharField(default='مركز عبور للرعاية والتأهيل', max_length=200, verbose_name='اسم الموقع (عربي)')),
                ('site_name_en', models.CharField(blank=True, default='Oboor Center for Care & Rehabilitation', max_length=200, verbose_name='اسم الموقع (إنجليزي)')),
                ('brand_desc_ar', models.TextField(blank=True, verbose_name='وصف المركز في الفوتر (عربي)')),
                ('brand_desc_en', models.TextField(blank=True, verbose_name='وصف المركز في الفوتر (إنجليزي)')),
                ('email', models.CharField(blank=True, max_length=120, verbose_name='البريد الإلكتروني')),
                ('phone_unified', models.CharField(blank=True, max_length=40, verbose_name='الرقم الموحّد')),
                ('phone_customer', models.CharField(blank=True, max_length=40, verbose_name='خدمة العملاء')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='واتساب (رقم wa.me)')),
                ('website', models.CharField(blank=True, max_length=120, verbose_name='الموقع الإلكتروني')),
                ('main_branch_ar', models.CharField(blank=True, max_length=200, verbose_name='الفرع الرئيسي (عربي)')),
                ('main_branch_en', models.CharField(blank=True, max_length=200, verbose_name='الفرع الرئيسي (إنجليزي)')),
                ('x_url', models.CharField(blank=True, max_length=200, verbose_name='رابط إكس (تويتر)')),
                ('instagram_url', models.CharField(blank=True, max_length=200, verbose_name='رابط انستغرام')),
                ('tiktok_url', models.CharField(blank=True, max_length=200, verbose_name='رابط تيك توك')),
                ('whatsapp_url', models.CharField(blank=True, max_length=200, verbose_name='رابط واتساب')),
                ('youtube_url', models.CharField(blank=True, max_length=200, verbose_name='رابط يوتيوب')),
                ('snapchat_url', models.CharField(blank=True, max_length=200, verbose_name='رابط سناب شات')),
                ('cta_admission_ar', models.CharField(blank=True, max_length=80, verbose_name='زر الالتحاق (عربي)')),
                ('cta_admission_en', models.CharField(blank=True, max_length=80, verbose_name='زر الالتحاق (إنجليزي)')),
                ('cta_contact_ar', models.CharField(blank=True, max_length=80, verbose_name='زر التواصل (عربي)')),
                ('cta_contact_en', models.CharField(blank=True, max_length=80, verbose_name='زر التواصل (إنجليزي)')),
                ('footer_quick_title_ar', models.CharField(blank=True, max_length=80, verbose_name='عنوان الروابط السريعة (عربي)')),
                ('footer_quick_title_en', models.CharField(blank=True, max_length=80, verbose_name='عنوان الروابط السريعة (إنجليزي)')),
                ('footer_services_title_ar', models.CharField(blank=True, max_length=80, verbose_name='عنوان الخدمات (عربي)')),
                ('footer_services_title_en', models.CharField(blank=True, max_length=80, verbose_name='عنوان الخدمات (إنجليزي)')),
                ('footer_contact_title_ar', models.CharField(blank=True, max_length=80, verbose_name='عنوان التواصل (عربي)')),
                ('footer_contact_title_en', models.CharField(blank=True, max_length=80, verbose_name='عنوان التواصل (إنجليزي)')),
                ('privacy_label_ar', models.CharField(blank=True, max_length=120, verbose_name='نص سياسة الخصوصية (عربي)')),
                ('privacy_label_en', models.CharField(blank=True, max_length=120, verbose_name='نص سياسة الخصوصية (إنجليزي)')),
                ('copyright_ar', models.TextField(blank=True, verbose_name='حقوق النشر (عربي)')),
                ('copyright_en', models.TextField(blank=True, verbose_name='حقوق النشر (إنجليزي)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='page',
            field=models.CharField(choices=[('home', 'الرئيسية'), ('success', 'قصص النجاح'), ('specialists', 'الأخصائيون'), ('assessment', 'التقييم'), ('branches', 'الفروع'), ('careers', 'الوظائف'), ('news', 'الأخبار'), ('header', 'الهيدر (القائمة العلوية)'), ('footer', 'الفوتر (التذييل)')], max_length=40, verbose_name='الصفحة'),
        ),
    ]
