# Generated by Django 5.1.4 on 2026-06-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_sitesettings_alter_sectionitem_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalservice',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='content/', verbose_name='رفع صورة'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='content/', verbose_name='رفع صورة'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='content/', verbose_name='رفع صورة'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='content/', verbose_name='رفع صورة'),
        ),
        migrations.AddField(
            model_name='programdetail',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='content/', verbose_name='رفع صورة'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='content/', verbose_name='رفع صورة'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='content/', verbose_name='رفع صورة'),
        ),
        migrations.AddField(
            model_name='technique',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='content/', verbose_name='رفع صورة'),
        ),
    ]
