# Generated by Django 5.1.15 on 2026-06-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_clinicalservice_image_file_galleryimage_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(max_length=40)),
                ('obj_id', models.IntegerField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لقطة محتوى افتراضية',
                'verbose_name_plural': 'لقطات المحتوى الافتراضية',
                'unique_together': {('type_key', 'obj_id')},
            },
        ),
    ]
