# Generated by Django 5.1.15 on 2026-06-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_contentsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalservice',
            name='about_list_ar',
            field=models.JSONField(blank=True, default=list, verbose_name='نقاط النبذة (عربي)'),
        ),
        migrations.AlterField(
            model_name='clinicalservice',
            name='about_list_en',
            field=models.JSONField(blank=True, default=list, verbose_name='نقاط النبذة (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='clinicalservice',
            name='about_tag_ar',
            field=models.JSONField(blank=True, default=dict, verbose_name='بطاقة مميّزة (عربي)'),
        ),
        migrations.AlterField(
            model_name='clinicalservice',
            name='about_tag_en',
            field=models.JSONField(blank=True, default=dict, verbose_name='بطاقة مميّزة (إنجليزي)'),
        ),
    ]
