# Generated by Django 5.1.15 on 2026-06-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_clinicalservice_about_list_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='gallery',
            field=models.JSONField(blank=True, default=list, verbose_name='معرض صور الفرع'),
        ),
    ]
