# Generated by Django 5.1.15 on 2026-06-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_branch_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض (lat)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول (lng)'),
        ),
    ]
