# Generated by Django 5.1.15 on 2026-06-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_branch_lat_branch_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='audience_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='الفئة المستهدفة (عربي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='audience_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الفئة المستهدفة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='body_ar',
            field=models.JSONField(blank=True, default=list, verbose_name='فقرات المحتوى (عربي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='body_en',
            field=models.JSONField(blank=True, default=list, verbose_name='فقرات المحتوى (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='learn_ar',
            field=models.JSONField(blank=True, default=list, verbose_name='ماذا ستتعلم / النقاط (عربي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='learn_en',
            field=models.JSONField(blank=True, default=list, verbose_name='ماذا ستتعلم / النقاط (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='location_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='المكان (عربي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='المكان (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='reg_status_ar',
            field=models.CharField(blank=True, max_length=160, verbose_name='حالة التسجيل (عربي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='reg_status_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='حالة التسجيل (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='seats_ar',
            field=models.CharField(blank=True, max_length=80, verbose_name='عدد المقاعد (عربي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='seats_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='عدد المقاعد (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='time_ar',
            field=models.CharField(blank=True, max_length=120, verbose_name='الوقت (عربي)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='time_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='الوقت (إنجليزي)'),
        ),
    ]
