# Generated by Django 5.1.15 on 2026-06-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_backfill_news_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='rating',
            field=models.CharField(blank=True, max_length=10, verbose_name='التقييم (مثل 4.8 — اتركه فارغاً لإخفائه)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='reviews_count',
            field=models.CharField(blank=True, max_length=20, verbose_name='عدد التقييمات (اتركه فارغاً لإخفائه)'),
        ),
    ]
