# Generated by Django 5.1.15 on 2026-06-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_sectionitem_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionitem',
            options={'ordering': ['page', 'order', 'id'], 'verbose_name': 'عنصر قسم', 'verbose_name_plural': 'عناصر أقسام الصفحات'},
        ),
    ]
