# Generated by Django 5.1.15 on 2026-06-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_seed_about_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='image',
            field=models.CharField(blank=True, max_length=300, verbose_name='مسار الصورة'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='content/', verbose_name='صورة القسم'),
        ),
    ]
