# Generated by Django 5.1.15 on 2026-06-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_about_programs_one_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdetail',
            name='about_ar',
            field=models.JSONField(blank=True, default=list, help_text='فقرات النبذة التعريفية أعلى الصفحة (قسم «عن البرنامج»).', verbose_name='نبذة (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='duration_ar',
            field=models.TextField(blank=True, help_text='نص يظهر في كارت «مدة البرنامج».', verbose_name='مدة البرنامج (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='methods_ar',
            field=models.JSONField(blank=True, default=list, help_text='أساليب/مناهج علمية — كارت «المنهج العلمي» (لكل عنصر: اسم عريض اختياري + وصف).', verbose_name='المنهج العلمي (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='philosophy_ar',
            field=models.JSONField(blank=True, default=list, help_text='بطاقات فلسفة البرنامج (تظهر في القسم الغامق).', verbose_name='الفلسفة (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='philosophy_intro_ar',
            field=models.TextField(blank=True, help_text='جملة تمهيدية لقسم «فلسفة البرنامج».', verbose_name='مقدمة الفلسفة (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='stations_ar',
            field=models.JSONField(blank=True, default=list, help_text='قائمة المحطات/الخطوات التطبيقية — القسم يظهر فقط إذا أضفت عناصر.', verbose_name='المحطات التطبيقية (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='stations_intro_ar',
            field=models.TextField(blank=True, help_text='جملة تمهيدية لقسم «المحطات التطبيقية».', verbose_name='مقدمة المحطات (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='subtitle_ar',
            field=models.TextField(help_text='سطر تحت العنوان في أعلى صفحة البرنامج (الهيرو).', verbose_name='العنوان الفرعي (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='target_ar',
            field=models.TextField(blank=True, help_text='وصف الفئة المستهدفة — يظهر في كارت «الفئة المستهدفة».', verbose_name='الفئة المستهدفة (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='target_list_ar',
            field=models.JSONField(blank=True, default=list, help_text='نقاط تفصيلية تظهر كقائمة داخل كارت «الفئة المستهدفة» (اتركها فارغة إن لم تكن مطلوبة).', verbose_name='قائمة الفئة المستهدفة (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='target_tags_ar',
            field=models.JSONField(blank=True, default=list, help_text='وسوم صغيرة تظهر أسفل وصف الفئة المستهدفة.', verbose_name='وسوم الفئة المستهدفة (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='training_areas_ar',
            field=models.JSONField(blank=True, default=list, help_text='بطاقات مجالات التدريب (لكل مجال: اسم + وصف).', verbose_name='مجالات التدريب (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='training_intro_ar',
            field=models.TextField(blank=True, help_text='جملة تمهيدية لقسم «مجالات التدريب».', verbose_name='مقدمة مجالات التدريب (عربي)'),
        ),
    ]
