# Generated by Django 5.1.15 on 2026-06-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_seed_careers_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='city_ar',
            field=models.CharField(help_text='يظهر في: الوسوم العلوية + جدول «تفاصيل الوظيفة» + كارت «ملخص الوظيفة» الجانبي.', max_length=300, verbose_name='المدينة (عربي)'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='date_ar',
            field=models.CharField(blank=True, help_text='يظهر في: الوسوم العلوية + جدول «تفاصيل الوظيفة».', max_length=300, verbose_name='تاريخ الطرح (عربي)'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='department_ar',
            field=models.CharField(help_text='يظهر في: وسوم أعلى الصفحة + جدول «تفاصيل الوظيفة».', max_length=300, verbose_name='القسم (عربي)'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='description_ar',
            field=models.TextField(help_text='فقرة «الوصف الوظيفي» في متن الصفحة.', verbose_name='الوصف الوظيفي (عربي)'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='employment_ar',
            field=models.CharField(help_text='يظهر في: الوسوم العلوية + جدول «تفاصيل الوظيفة» + كارت «ملخص الوظيفة».', max_length=300, verbose_name='نوع الدوام (عربي)'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='experience_ar',
            field=models.CharField(help_text='سطر قصير (مثل: سنتان فأكثر) — يظهر في جدول «تفاصيل الوظيفة» + كارت «ملخص الوظيفة». (قائمة المتطلبات منفصلة بالأسفل.)', max_length=300, verbose_name='الخبرة المطلوبة (عربي)'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='is_new',
            field=models.BooleanField(default=False, help_text='عند تفعيله يظهر وسم «جديد» بجوار الوظيفة في القائمة.', verbose_name='جديد'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='requirements_ar',
            field=models.JSONField(blank=True, default=list, help_text='قائمة «الخبرة المطلوبة» (النقاط) في متن الصفحة.', verbose_name='المتطلبات (عربي)'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='responsibilities_ar',
            field=models.JSONField(blank=True, default=list, help_text='قائمة «المهام والمسؤوليات» في متن الصفحة.', verbose_name='المهام والمسؤوليات (عربي)'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='start_date_ar',
            field=models.CharField(blank=True, help_text='يظهر في: جدول «تفاصيل الوظيفة» + كارت «ملخص الوظيفة».', max_length=300, verbose_name='تاريخ المباشرة المتوقع (عربي)'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='title_ar',
            field=models.CharField(help_text='عنوان الوظيفة — يظهر في عنوان الصفحة وفي قائمة الوظائف.', max_length=300, verbose_name='المسمى الوظيفي (عربي)'),
        ),
    ]
