# Generated by Django 5.1.15 on 2026-06-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_seed_page_heroes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='page',
            field=models.CharField(choices=[('home', 'الرئيسية'), ('about', 'عن عبور'), ('success', 'قصص النجاح'), ('specialists', 'الأخصائيون'), ('assessment', 'التقييم'), ('branches', 'الفروع'), ('careers', 'الوظائف'), ('news', 'الأخبار'), ('programs', 'البرامج'), ('header', 'الهيدر (القائمة العلوية)'), ('footer', 'الفوتر (التذييل)')], max_length=40, verbose_name='الصفحة'),
        ),
    ]
