# Generated by Django 5.1.15 on 2026-06-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_seed_branch_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdetail',
            name='philosophy_ar',
            field=models.JSONField(blank=True, default=list, help_text='نقاط فلسفة البرنامج — كل نقطة تظهر كبطاقة في القسم الغامق بصفحة البرنامج (رؤية المركز وأسلوبه). اتركها فارغة إن لم يكن للبرنامج قسم فلسفة.', verbose_name='الفلسفة (عربي)'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='philosophy_intro_ar',
            field=models.TextField(blank=True, help_text='جملة تمهيدية تظهر أعلى قسم «فلسفة البرنامج» (القسم الغامق في صفحة البرنامج).', verbose_name='مقدمة الفلسفة (عربي)'),
        ),
    ]
