# Generated by Django 5.1.15 on 2026-06-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_remove_assessment_prelim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='featured',
            field=models.BooleanField(default=False, help_text='عند تفعيله يظهر هذا العنصر كبطاقة كبيرة مميّزة في أعلى قسمه (الورش أو المقالات) بدل كارت عادي. فعّله لعنصر واحد فقط في كل قسم.', verbose_name='مميّز'),
        ),
    ]
