# Generated by Django 5.1.15 on 2026-06-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_alter_newsarticle_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(max_length=40)),
                ('obj_id', models.CharField(max_length=40)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مسودّة معاينة',
                'verbose_name_plural': 'مسودّات المعاينة',
                'unique_together': {('type_key', 'obj_id')},
            },
        ),
    ]
