# Generated by Django 5.1.15 on 2026-07-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_previewdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='map_url',
            field=models.URLField(blank=True, help_text='اختياري — الصق رابط المكان من خرائط جوجل (Share ثم Copy link). عند إضافته يصبح اسم المكان رابطاً يفتح الخريطة؛ إن تُرك فارغاً يظهر الاسم كنص فقط.', max_length=500, verbose_name='رابط الموقع على الخريطة'),
        ),
    ]
