# Generated by Django 5.1.15 on 2026-07-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_newsarticle_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='cta_href',
            field=models.CharField(blank=True, help_text='وجهة الزر عند الضغط: رابط داخلي مثل /programs أو /branches، أو رابط كامل https://…. إن تُرك فارغاً يذهب إلى صفحة البرامج.', max_length=300, verbose_name='رابط زر الإجراء'),
        ),
    ]
