# Generated by Django 5.1.15 on 2026-07-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_heroslide_cta_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='رقم الواتساب بالصيغة الدولية بدون + أو مسافات (مثال: 966920003452). يُستخدم في كل أزرار «تواصل عبر واتساب» بالموقع. إن تُرك فارغاً يُستخدم الرقم الافتراضي.', max_length=40, verbose_name='رقم الواتساب'),
        ),
    ]
