# Generated by Django 5.1.15 on 2026-07-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_alter_sitesettings_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='هذا الحقل يتحكّم في رقم الواتساب على مستوى الموقع كله: كل أزرار «تواصل عبر واتساب»، والزر العائم، ورابط الواتساب في الفوتر — تتغيّر جميعها من هنا. اكتب الرقم بالصيغة الدولية بدون + أو مسافات (مثال: 966920003452). إن تُرك فارغاً يُستخدم الرقم الافتراضي.', max_length=40, verbose_name='رقم الواتساب'),
        ),
    ]
