# Generated by Django 5.1.15 on 2026-07-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_alter_sitesettings_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.CharField(blank=True, max_length=200, verbose_name='بريد الفرع الإلكتروني'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.CharField(blank=True, max_length=200, verbose_name='مدير الفرع'),
        ),
        migrations.AddField(
            model_name='branch',
            name='map_url',
            field=models.CharField(blank=True, help_text='رابط موقع الفرع على خرائط جوجل — يُستخدم لزر «الاتجاهات».', max_length=500, verbose_name='رابط الموقع على الخريطة'),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone_evening',
            field=models.CharField(blank=True, max_length=80, verbose_name='رقم المساء'),
        ),
    ]
