# Generated by Django 5.1.15 on 2026-07-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_branch_manager_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='badge_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='الشارة العلوية (عربي)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='زر الإجراء (عربي)'),
        ),
    ]
