# Generated by Django 5.1.15 on 2026-07-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_seed_branch_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='service_cards',
            field=models.JSONField(blank=True, default=list, verbose_name='كروت خدمات الفرع'),
        ),
    ]
