# Generated by Django 5.1.15 on 2026-07-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_seed_branch_service_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='accreditations',
            field=models.JSONField(blank=True, default=list, verbose_name='الاعتمادات (ملف الفرع)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='journey',
            field=models.JSONField(blank=True, default=list, verbose_name='رحلة التأهيل (ملف الفرع)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='profile_intro_ar',
            field=models.TextField(blank=True, verbose_name='نبذة ملف الفرع (عربي)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='profile_intro_en',
            field=models.TextField(blank=True, verbose_name='نبذة ملف الفرع (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='profile_stats',
            field=models.JSONField(blank=True, default=list, verbose_name='إحصائيات ملف الفرع'),
        ),
    ]
