# Generated by Django 5.1.15 on 2026-07-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_seed_branch_profile_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='distinctions',
            field=models.JSONField(blank=True, default=list, verbose_name='ما يميّز الفرع'),
        ),
        migrations.AddField(
            model_name='branch',
            name='success_heading_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='عنوان قصص النجاح (عربي)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='success_heading_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='عنوان قصص النجاح (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='success_sub_ar',
            field=models.TextField(blank=True, verbose_name='وصف قصص النجاح (عربي)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='success_sub_en',
            field=models.TextField(blank=True, verbose_name='وصف قصص النجاح (إنجليزي)'),
        ),
    ]
