# Generated by Django 5.1.15 on 2026-07-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_seed_specialists_join_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='badge_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='الوسم (عربي)'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='badge_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='الوسم (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='journey_ar',
            field=models.TextField(blank=True, verbose_name='رحلة العلاج (عربي)'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='journey_en',
            field=models.TextField(blank=True, verbose_name='رحلة العلاج (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='program_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='البرنامج (عربي)'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='program_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='البرنامج (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='results_ar',
            field=models.JSONField(blank=True, default=list, verbose_name='أبرز النتائج (عربي)'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='results_en',
            field=models.JSONField(blank=True, default=list, verbose_name='أبرز النتائج (إنجليزي)'),
        ),
    ]
