# Generated by Django 5.1.15 on 2026-07-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_seed_contact_feature_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='مُفعّل')),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='خادم SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='المنفذ (Port)')),
                ('security', models.CharField(choices=[('tls', 'TLS (STARTTLS)'), ('ssl', 'SSL'), ('none', 'بدون تشفير')], default='tls', max_length=10, verbose_name='نوع التشفير')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='اسم المستخدم (الإيميل)')),
                ('password', models.CharField(blank=True, max_length=500, verbose_name='كلمة المرور (App Password)')),
                ('from_email', models.CharField(blank=True, help_text='إن تُرك فارغًا يُستخدم اسم المستخدم', max_length=200, verbose_name='عنوان المُرسِل (From)')),
                ('from_name', models.CharField(blank=True, default='مركز عبور للرعاية والتأهيل', max_length=200, verbose_name='اسم المُرسِل الظاهر')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات البريد (SMTP)',
                'verbose_name_plural': 'إعدادات البريد (SMTP)',
            },
        ),
    ]
