# Generated by Django 5.1.4 on 2026-06-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=200, verbose_name='اسم الطفل')),
                ('child_age', models.CharField(blank=True, max_length=40, verbose_name='العمر')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='الجنس')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='المدينة')),
                ('branch', models.CharField(blank=True, max_length=120, verbose_name='الفرع')),
                ('parent_name', models.CharField(max_length=200, verbose_name='ولي الأمر')),
                ('phone', models.CharField(max_length=40, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('case_type', models.CharField(blank=True, max_length=120, verbose_name='نوع الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
            ],
            options={
                'verbose_name': 'طلب التحاق',
                'verbose_name_plural': 'طلبات الالتحاق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(max_length=120, verbose_name='نوع التقييم')),
                ('assessment_slug', models.CharField(blank=True, max_length=60, verbose_name='المعرّف')),
                ('level', models.CharField(blank=True, choices=[('high', 'مرتفع'), ('medium', 'متوسط'), ('low', 'منخفض')], max_length=10, verbose_name='مستوى الحالة')),
                ('score', models.IntegerField(default=0, verbose_name='الدرجة')),
                ('answers', models.JSONField(blank=True, default=list, verbose_name='الإجابات')),
                ('parent_name', models.CharField(max_length=200, verbose_name='ولي الأمر')),
                ('phone', models.CharField(max_length=40, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('child_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الطفل')),
                ('age', models.CharField(blank=True, max_length=40, verbose_name='العمر')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='الجنس')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='المدينة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
            ],
            options={
                'verbose_name': 'نتيجة تقييم',
                'verbose_name_plural': 'نتائج التقييم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=40, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('branch', models.CharField(blank=True, max_length=120, verbose_name='الفرع')),
                ('type', models.CharField(blank=True, max_length=60, verbose_name='النوع')),
                ('message', models.TextField(blank=True, verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=200, verbose_name='الوظيفة')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=40, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='المدينة')),
                ('current_role', models.CharField(blank=True, max_length=200, verbose_name='المسمى الحالي')),
                ('experience', models.CharField(blank=True, max_length=80, verbose_name='الخبرة')),
                ('about', models.TextField(blank=True, verbose_name='نبذة')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='السيرة الذاتية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
            ],
            options={
                'verbose_name': 'طلب توظيف',
                'verbose_name_plural': 'طلبات التوظيف',
                'ordering': ['-created_at'],
            },
        ),
    ]
