# Generated by Django 5.1.15 on 2026-07-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='branch',
            field=models.CharField(blank=True, max_length=120, verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='branch',
            field=models.CharField(blank=True, max_length=120, verbose_name='الفرع'),
        ),
    ]
