# -*- coding: utf-8 -*-
from django.core.management.base import BaseCommand
from content.m_careers import JobOpening

# slug, is_new, ar(title, department, city, employment, experience, date, start_date,
#   description, responsibilities[], requirements[]), en(...)
JOBS = [
    ("speech-therapist", True,
     ("أخصائي/ة علاج النطق والتخاطب", "قسم علاج النطق", "الرياض", "دوام كامل",
      "سنتان فأكثر", "١٠ مارس ٢٠٢٥", "١ أبريل ٢٠٢٥",
      "يسعى مركز عبور للحصول على أخصائي/ة علاج نطق وتخاطب متخصص في تقييم وعلاج اضطرابات النطق واللغة والتواصل لدى الأطفال. يُعدّ هذا الدور ركيزةً أساسيةً في منظومة الرعاية الشاملة، حيث يُشارك الشاغل في وضع الخطط العلاجية الفردية ومتابعة تقدم المستفيدين ضمن فريق متعدد التخصصات.",
      [
          "إجراء التقييم الشامل لاضطرابات النطق واللغة والتواصل",
          "تصميم وتنفيذ خطط علاجية فردية لكل طفل",
          "إرشاد الأسر ومتابعة تطبيق التمارين المنزلية",
          "توثيق الجلسات وإعداد التقارير الدورية",
          "العمل ضمن الفريق متعدد التخصصات",
      ],
      [
          "بكالوريوس في علوم النطق والتخاطب أو ما يعادله",
          "خبرة سنتان فأكثر في التعامل مع الأطفال",
          "ترخيص ساري من هيئة التخصصات الصحية",
          "إتقان أساليب التواصل المعزز والبديل (AAC)",
      ]),
     ("Speech & Language Therapist", "Speech Therapy Department", "Riyadh", "Full-time",
      "2+ years", "10 March 2025", "1 April 2025",
      "Oboor Center is seeking a Speech & Language Therapist specialized in assessing and treating speech, language, and communication disorders in children. This role is a cornerstone of our comprehensive care system, where the postholder contributes to developing individual treatment plans and tracking beneficiaries' progress within a multidisciplinary team.",
      [
          "Conduct comprehensive assessment of speech, language, and communication disorders",
          "Design and implement individual treatment plans for each child",
          "Guide families and follow up on the application of home exercises",
          "Document sessions and prepare periodic reports",
          "Work within the multidisciplinary team",
      ],
      [
          "Bachelor's degree in Speech & Language Sciences or equivalent",
          "2+ years of experience working with children",
          "Valid license from the Saudi Commission for Health Specialties",
          "Proficiency in Augmentative and Alternative Communication (AAC) methods",
      ])),
    ("occupational-therapist", True,
     ("أخصائي/ة علاج وظيفي", "قسم العلاج الوظيفي", "جدة", "دوام كامل",
      "٣ سنوات فأكثر", "٨ مارس ٢٠٢٥", "١ أبريل ٢٠٢٥",
      "نبحث عن أخصائي/ة علاج وظيفي شغوف بتأهيل الأطفال وتنمية مهاراتهم الحركية الدقيقة والحسية واليومية. يُشارك الشاغل في تمكين المستفيدين من أداء أنشطة الحياة اليومية باستقلالية ضمن بيئة علاجية محفّزة.",
      [
          "تقييم المهارات الحركية والحسية ومهارات العناية بالذات",
          "إعداد برامج التكامل الحسي والعلاج الوظيفي الفردية",
          "تدريب الأسرة على الأنشطة الداعمة في المنزل",
          "متابعة تقدم الحالة وتعديل الخطة العلاجية",
          "التنسيق مع الفريق العلاجي متعدد التخصصات",
      ],
      [
          "بكالوريوس في العلاج الوظيفي",
          "خبرة ٣ سنوات فأكثر في تأهيل الأطفال",
          "ترخيص ساري من هيئة التخصصات الصحية",
          "خبرة في برامج التكامل الحسي",
      ]),
     ("Occupational Therapist", "Occupational Therapy Department", "Jeddah", "Full-time",
      "3+ years", "8 March 2025", "1 April 2025",
      "We are looking for an Occupational Therapist passionate about rehabilitating children and developing their fine motor, sensory, and daily living skills. The postholder helps empower beneficiaries to perform daily life activities independently within a stimulating therapeutic environment.",
      [
          "Assess motor, sensory, and self-care skills",
          "Prepare individual sensory integration and occupational therapy programs",
          "Train families on supportive activities at home",
          "Track case progress and adjust the treatment plan",
          "Coordinate with the multidisciplinary therapy team",
      ],
      [
          "Bachelor's degree in Occupational Therapy",
          "3+ years of experience in children's rehabilitation",
          "Valid license from the Saudi Commission for Health Specialties",
          "Experience in sensory integration programs",
      ])),
    ("physical-therapist", False,
     ("أخصائي/ة علاج طبيعي", "قسم العلاج الطبيعي", "الرياض", "دوام كامل",
      "سنتان فأكثر", "٥ مارس ٢٠٢٥", "٢٥ مارس ٢٠٢٥",
      "يسعى مركز عبور لاستقطاب أخصائي/ة علاج طبيعي متخصص في تأهيل الحالات العصبية والعضلية الهيكلية لدى الأطفال، للمساهمة في تحسين القدرات الحركية والوظيفية للمستفيدين.",
      [
          "إجراء التقييم الحركي الشامل للأطفال",
          "تصميم برامج تأهيل حركي فردية",
          "استخدام التقنيات والمعدات العلاجية الحديثة",
          "متابعة التقدم وتوثيق النتائج",
          "إرشاد الأسر حول التمارين المنزلية",
      ],
      [
          "بكالوريوس في العلاج الطبيعي",
          "خبرة سنتان فأكثر في تأهيل الأطفال",
          "ترخيص ساري من هيئة التخصصات الصحية",
          "معرفة بأساليب التأهيل العصبي التطوري",
      ]),
     ("Physical Therapist", "Physical Therapy Department", "Riyadh", "Full-time",
      "2+ years", "5 March 2025", "25 March 2025",
      "Oboor Center seeks to recruit a Physical Therapist specialized in rehabilitating neurological and musculoskeletal conditions in children, to contribute to improving beneficiaries' motor and functional abilities.",
      [
          "Conduct comprehensive motor assessment for children",
          "Design individual motor rehabilitation programs",
          "Use modern therapeutic techniques and equipment",
          "Track progress and document outcomes",
          "Guide families on home exercises",
      ],
      [
          "Bachelor's degree in Physical Therapy",
          "2+ years of experience in children's rehabilitation",
          "Valid license from the Saudi Commission for Health Specialties",
          "Knowledge of Neurodevelopmental Treatment (NDT) methods",
      ])),
    ("aba-specialist", True,
     ("أخصائي/ة تحليل سلوك تطبيقي (ABA)", "قسم تعديل السلوك", "الشرقية", "دوام كامل",
      "٣ سنوات فأكثر", "٢ مارس ٢٠٢٥", "٢٠ مارس ٢٠٢٥",
      "نبحث عن أخصائي/ة تحليل سلوك تطبيقي معتمد للعمل مع الأطفال ذوي اضطراب طيف التوحد والاضطرابات السلوكية، وتصميم برامج تعديل السلوك القائمة على الأدلة.",
      [
          "إجراء التقييم الوظيفي للسلوك (FBA)",
          "تصميم وتنفيذ خطط تعديل السلوك الفردية",
          "تدريب الكوادر والأسر على تطبيق البرامج",
          "جمع البيانات وتحليلها لقياس التقدم",
          "العمل ضمن فريق متعدد التخصصات",
      ],
      [
          "بكالوريوس أو ماجستير في علم النفس أو التربية الخاصة",
          "خبرة ٣ سنوات فأكثر في تحليل السلوك التطبيقي",
          "شهادة BCBA أو ما يعادلها (يُفضّل)",
          "خبرة في التعامل مع اضطراب طيف التوحد",
      ]),
     ("Applied Behavior Analysis (ABA) Specialist", "Behavior Modification Department", "Eastern Province", "Full-time",
      "3+ years", "2 March 2025", "20 March 2025",
      "We are looking for a certified Applied Behavior Analysis specialist to work with children with Autism Spectrum Disorder and behavioral disorders, and to design evidence-based behavior modification programs.",
      [
          "Conduct Functional Behavior Assessment (FBA)",
          "Design and implement individual behavior modification plans",
          "Train staff and families on program implementation",
          "Collect and analyze data to measure progress",
          "Work within a multidisciplinary team",
      ],
      [
          "Bachelor's or Master's degree in Psychology or Special Education",
          "3+ years of experience in applied behavior analysis",
          "BCBA certification or equivalent (preferred)",
          "Experience working with Autism Spectrum Disorder",
      ])),
    ("psychologist", False,
     ("أخصائي/ة نفسي", "القسم النفسي", "الرياض", "دوام جزئي",
      "٣ سنوات فأكثر", "٣ مارس ٢٠٢٥", "١٥ مارس ٢٠٢٥",
      "يسعى مركز عبور للحصول على معالج أو معالجة نفسية متخصصة في التعامل مع الأطفال وذوي الاحتياجات الخاصة. يُعدّ هذا الدور ركيزةً أساسيةً في منظومة الرعاية الشاملة التي يقدمها المركز، حيث يُشارك الشاغل في تقديم الدعم النفسي للمستفيدين وأسرهم.",
      [
          "إجراء الجلسات التشخيصية والعلاجية للأطفال باستخدام أساليب علاجية معتمدة",
          "تقديم الإرشاد النفسي لأسر المستفيدين",
          "العمل ضمن الفريق متعدد التخصصات لتقديم خطط رعاية شاملة",
          "توثيق الجلسات وإعداد التقارير النفسية",
          "المشاركة في جلسات الحالة والاجتماعات الفريقية",
      ],
      [
          "بكالوريوس أو ماجستير في علم النفس الإكلينيكي أو الإرشاد النفسي",
          "خبرة ٣ سنوات فأكثر في التعامل مع الأطفال",
          "ترخيص ساري من جهة معنية معتمدة",
          "إتقان تقنيات العلاج المعرفي السلوكي (CBT) والعلاج باللعب",
      ]),
     ("Psychologist", "Psychology Department", "Riyadh", "Part-time",
      "3+ years", "3 March 2025", "15 March 2025",
      "Oboor Center is seeking a psychologist specialized in working with children and people with special needs. This role is a cornerstone of the comprehensive care system the center provides, where the postholder contributes to delivering psychological support to beneficiaries and their families.",
      [
          "Conduct diagnostic and therapeutic sessions for children using approved therapeutic methods",
          "Provide psychological counseling to beneficiaries' families",
          "Work within the multidisciplinary team to deliver comprehensive care plans",
          "Document sessions and prepare psychological reports",
          "Participate in case sessions and team meetings",
      ],
      [
          "Bachelor's or Master's degree in Clinical Psychology or Psychological Counseling",
          "3+ years of experience working with children",
          "Valid license from a relevant accredited authority",
          "Proficiency in Cognitive Behavioral Therapy (CBT) and play therapy techniques",
      ])),
    ("pediatric-nurse", False,
     ("ممرض/ة أطفال", "قسم التمريض", "الرياض", "دوام كامل",
      "سنة فأكثر", "٢٥ فبراير ٢٠٢٥", "١٥ مارس ٢٠٢٥",
      "نبحث عن ممرض/ة أطفال للانضمام إلى فريق التمريض، لتقديم رعاية تمريضية متخصصة وآمنة للأطفال خلال رحلتهم التأهيلية داخل المركز.",
      [
          "تقديم الرعاية التمريضية اليومية للمستفيدين",
          "متابعة الحالة الصحية وإدارة الأدوية والجرعات",
          "التنسيق مع الفريق الطبي والعلاجي",
          "توثيق الملاحظات الصحية والتقارير",
          "تطبيق معايير السلامة ومكافحة العدوى",
      ],
      [
          "بكالوريوس أو دبلوم في التمريض",
          "خبرة سنة فأكثر (يُفضّل في رعاية الأطفال)",
          "تصنيف ساري من الهيئة السعودية للتخصصات الصحية",
          "مهارات تواصل عالية مع الأطفال وأسرهم",
      ]),
     ("Pediatric Nurse", "Nursing Department", "Riyadh", "Full-time",
      "1+ year", "25 February 2025", "15 March 2025",
      "We are looking for a Pediatric Nurse to join the nursing team, to provide specialized and safe nursing care for children throughout their rehabilitation journey at the center.",
      [
          "Provide daily nursing care to beneficiaries",
          "Monitor health conditions and manage medications and dosages",
          "Coordinate with the medical and therapy team",
          "Document health observations and reports",
          "Apply safety and infection control standards",
      ],
      [
          "Bachelor's degree or diploma in Nursing",
          "1+ year of experience (preferably in pediatric care)",
          "Valid classification from the Saudi Commission for Health Specialties",
          "Strong communication skills with children and their families",
      ])),
    ("special-education", False,
     ("أخصائي/ة تربية خاصة", "القسم التربوي", "جدة", "دوام كامل",
      "سنتان فأكثر", "٢٠ فبراير ٢٠٢٥", "١٠ مارس ٢٠٢٥",
      "نبحث عن أخصائي/ة تربية خاصة لإعداد وتنفيذ الخطط التربوية الفردية للأطفال ذوي الاحتياجات الخاصة، ودعم اندماجهم الأكاديمي والاجتماعي.",
      [
          "إعداد الخطط التربوية الفردية (IEP) وتنفيذها",
          "تطبيق استراتيجيات التدريس الفردي والجماعي",
          "تقييم التقدم الأكاديمي والسلوكي للأطفال",
          "التعاون مع الأسرة والفريق العلاجي",
          "تهيئة الأطفال للاندماج في البيئة المدرسية",
      ],
      [
          "بكالوريوس في التربية الخاصة",
          "خبرة سنتان فأكثر في التعليم أو التأهيل",
          "معرفة بأساليب تعديل السلوك",
          "مهارات تخطيط وتقييم تربوي",
      ]),
     ("Special Education Specialist", "Educational Department", "Jeddah", "Full-time",
      "2+ years", "20 February 2025", "10 March 2025",
      "We are looking for a Special Education Specialist to prepare and implement individual education plans for children with special needs, and to support their academic and social integration.",
      [
          "Prepare and implement Individual Education Plans (IEP)",
          "Apply individual and group teaching strategies",
          "Assess children's academic and behavioral progress",
          "Collaborate with the family and the therapy team",
          "Prepare children for integration into the school environment",
      ],
      [
          "Bachelor's degree in Special Education",
          "2+ years of experience in education or rehabilitation",
          "Knowledge of behavior modification methods",
          "Educational planning and assessment skills",
      ])),
    ("client-coordinator", False,
     ("منسق/ة خدمة العملاء", "قسم خدمة العملاء", "الرياض", "دوام كامل",
      "سنة فأكثر", "١٨ فبراير ٢٠٢٥", "٥ مارس ٢٠٢٥",
      "نبحث عن منسق/ة خدمة عملاء لتقديم تجربة مميزة للمستفيدين وأسرهم، وإدارة الاستفسارات والمواعيد والتنسيق بين الأقسام بكفاءة واحترافية.",
      [
          "استقبال المستفيدين والرد على الاستفسارات",
          "إدارة جدولة المواعيد ومتابعتها",
          "التنسيق بين الأقسام لضمان سلاسة الخدمة",
          "متابعة رضا المستفيدين ومعالجة الملاحظات",
          "توثيق البيانات في الأنظمة المعتمدة",
      ],
      [
          "بكالوريوس في إدارة الأعمال أو مجال ذي صلة",
          "خبرة سنة فأكثر في خدمة العملاء",
          "مهارات تواصل وتنظيم عالية",
          "إجادة استخدام الحاسب والأنظمة المكتبية",
      ]),
     ("Customer Service Coordinator", "Customer Service Department", "Riyadh", "Full-time",
      "1+ year", "18 February 2025", "5 March 2025",
      "We are looking for a Customer Service Coordinator to deliver an outstanding experience for beneficiaries and their families, and to manage inquiries, appointments, and coordination between departments efficiently and professionally.",
      [
          "Welcome beneficiaries and respond to inquiries",
          "Manage appointment scheduling and follow-up",
          "Coordinate between departments to ensure smooth service",
          "Track beneficiary satisfaction and address feedback",
          "Document data in the approved systems",
      ],
      [
          "Bachelor's degree in Business Administration or a related field",
          "1+ year of experience in customer service",
          "Strong communication and organizational skills",
          "Proficiency in using computers and office systems",
      ])),
]


class Command(BaseCommand):
    help = "Seed the JobOpening table from the original site careers content."

    def handle(self, *args, **opts):
        created = updated = 0
        for order, (slug, is_new, ar, en) in enumerate(JOBS):
            _, was_created = JobOpening.objects.update_or_create(
                slug=slug,
                defaults=dict(
                    is_new=is_new, order=order, published=True,
                    title_ar=ar[0], department_ar=ar[1], city_ar=ar[2],
                    employment_ar=ar[3], experience_ar=ar[4], date_ar=ar[5],
                    start_date_ar=ar[6], description_ar=ar[7],
                    responsibilities_ar=ar[8], requirements_ar=ar[9],
                    title_en=en[0], department_en=en[1], city_en=en[2],
                    employment_en=en[3], experience_en=en[4], date_en=en[5],
                    start_date_en=en[6], description_en=en[7],
                    responsibilities_en=en[8], requirements_en=en[9],
                ),
            )
            created += was_created
            updated += (not was_created)
        self.stdout.write(self.style.SUCCESS(f"Seeded careers: {created} created, {updated} updated."))
