# -*- coding: utf-8 -*-
import json
from django.core.management.base import BaseCommand
from content.m_branches import Branch

# قائمة الخدمات العامة الموحّدة (الشيت لا يحدّد خدمات لكل فرع)
DEFAULT_SERVICES = ["التدخل المبكر", "تخاطب ولغة", "علاج وظيفي", "تكامل حسي", "تعديل سلوك"]

DATA = json.loads(r"""[
 {
  "name": "مركز فرع عبور العزيزية  للرعاية النهارية",
  "region": "الرياض",
  "city": "العزيزية",
  "address": "منطقة الرياض - حي العزيزية - طريق النصر",
  "manager": "أ. مريم العليقي",
  "phone": "555608695",
  "phone_evening": "579844998",
  "email": "Oboor.alaziziyah@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/vjQqr1vtw7L9AeZUA?g_st=iw",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز فرع  عبور نمار  للرعاية النهارية",
  "region": "الرياض",
  "city": "نمار",
  "address": "منطقة الرياض - حي نمار - طريق نجم الدين",
  "manager": "أ. أميرة عيضة المالكي",
  "phone": "553990209",
  "phone_evening": "556550932",
  "email": "oboor.nemar@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/xRzvZw1FA45C5wLi9?g_st=iw",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز فرع عبور ظهرة لبن  للرعاية النهارية",
  "region": "الرياض",
  "city": "ظهرة لبن",
  "address": "منطقة الرياض - حي ظهرة لبن - شارع نجران",
  "manager": "أ.العنود القحطاني",
  "phone": "555259611",
  "phone_evening": "536487581",
  "email": "rep.labn@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/4KkiUUU5GcQcua6C9?g_st=iw",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز فرع عبور الروضة  للرعاية النهارية",
  "region": "الرياض",
  "city": "الروضة",
  "address": "منطقة الرياض - حي الروضه - مخرج 11 طريق الدائري الشرقي",
  "manager": "أ.اماني الشهري",
  "phone": "555256411",
  "phone_evening": "555032398",
  "email": "oboor.rawda@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/ETWVnEcu7qbjMzeT8?g_st=iw",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز فرع عبور المعيزلية  للرعاية النهارية",
  "region": "الرياض",
  "city": "المعيزلية",
  "address": "منطقة الرياض - حي المعيزلية - شارع فنون",
  "manager": "أ. مها مبارك ال شوغب",
  "phone": "553553209",
  "phone_evening": "541012037",
  "email": "almaizilah@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/QAPwtSzhtkthnWfR7?g_st=ipc",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور  النرجس  للرعاية النهارية",
  "region": "الرياض",
  "city": "النرجس",
  "address": "منطقة الرياض - حي النرجس - شارع الأمير سعود بن عبدالله الجلوي",
  "manager": "أ. أسيل سعود الراشد",
  "phone": "555258611",
  "phone_evening": "555257611",
  "email": "oboor.alnarjis@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/exrTahmyTdiGfLdW8",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز فرع عبور الملقا  للرعاية النهارية",
  "region": "الرياض",
  "city": "الملقا",
  "address": "منطقة الرياض- الملقا -وادي وج،، الرياض",
  "manager": "أ. لطيفة الصالح",
  "phone": "550287769",
  "phone_evening": "",
  "email": "oboor.almalqa@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/RfbfXbniNNEa4qxq6",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز عبور المرسلات للرعاية النهارية",
  "region": "الرياض",
  "city": "المرسلات",
  "address": "الرياض - حي المرسلات",
  "manager": "أ.رجاء سعد القحطاني",
  "phone": "553642443",
  "phone_evening": "",
  "email": "almursalat@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/B5v2cjGSHRj2SzVm6?g_st=ipc",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز عبور السلام للرعاية النهارية",
  "region": "الرياض",
  "city": "السلام",
  "address": "الرياض - حي السلام",
  "manager": "أ. شذى العصيمي",
  "phone": "533130590",
  "phone_evening": "",
  "email": "alsalam@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/itJBiVWSqFYipxQq8?g_st=ipc",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز فرع عبور المجمعة  للرعاية النهارية",
  "region": "الرياض",
  "city": "المجمعة",
  "address": "محافظة المجمعة - حي الملك عبد الله - شارع الأمير ثنيان بن سعود",
  "manager": "أ.نورة العيباني",
  "phone": "555124126",
  "phone_evening": "553256406",
  "email": "Majmaah@hdc.com.sa",
  "map_url": "https://maps.app.goo.gl/gueMettMzW1tzswo8?g_st=ic",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور وادي الدواسر للرعاية النهارية",
  "region": "الرياض",
  "city": "وادي الدواسر",
  "address": "طريق دله - حي الورود",
  "manager": "أ.عبير مرزوق",
  "phone": "500029085",
  "phone_evening": "",
  "email": "wadi.dwasr@hdc.com.sa",
  "map_url": "https://maps.app.goo.gl/LL2SdCSxwqt9Snuy8",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور النرجس جنوب الملك سلمان للرعاية النهارية",
  "region": "الرياض",
  "city": "النرجس جنوب الملك سلمان",
  "address": "الرياض  النرجس، طريق الأمير فيصل بن بندر بن عبدالعزيز،",
  "manager": "أ.أشواق المعمر",
  "phone": "535162373",
  "phone_evening": "",
  "email": "oboor.alnarjis2@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/eZS6ecmU2zp1UH8T7",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور العريجاء  للرعاية النهارية",
  "region": "الرياض",
  "city": "العريجاء",
  "address": "الرياض  العريجاء الوسطى، طريق الامير مساعد بن عبدالرحمن بن فيصل،",
  "manager": "أ.بجداء الهدباني",
  "phone": "539803371",
  "phone_evening": "573653319",
  "email": "oboor.aluraija@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/C4mHokcmd2YLTrJi7",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور بريدة للرعاية النهارية",
  "region": "القصيم",
  "city": "بريدة",
  "address": "منطقة القصيم - مدينة بريدة - حي النهضة - شارع أبي بكر الصديق",
  "manager": "أ.أمجاد الحربي",
  "phone": "500614855",
  "phone_evening": "551143188",
  "email": "qassim@hdc.com.sa",
  "map_url": "https://maps.app.goo.gl/RAK9nwS5gcpKDKts9?g_st=ipc",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور الرس  للرعاية النهارية",
  "region": "القصيم",
  "city": "الرس",
  "address": "منطقة القصيم - محافظة الرس - حي السعادة - شارع عبدالرحمن بن عوف",
  "manager": "أ.ندى الحربي",
  "phone": "555015057",
  "phone_evening": "",
  "email": "oboor.alrass@hdc.edu.sa",
  "map_url": "https://maps.google.com/?q=25.867300,43.486900",
  "lat": 25.8673,
  "lng": 43.4869
 },
 {
  "name": "مركز  فرع عبور محايل عسير للرعاية النهارية",
  "region": "عسير",
  "city": "محايل عسير",
  "address": "منطقة عسير  -محايل عسير -  الوعد،",
  "manager": "أ.شمعة دعبش",
  "phone": "532865692",
  "phone_evening": "",
  "email": "muhayil.asir@hdc.com.sa",
  "map_url": "https://maps.google.com/?q=18.564400,42.066509",
  "lat": 18.5644,
  "lng": 42.066509
 },
 {
  "name": "مركز  فرع عبور بيشة  للرعاية النهارية",
  "region": "عسير",
  "city": "بيشة",
  "address": "منطقة عسير - محافظة بيشة - حي الخزامى - طريق الملك سعود",
  "manager": "بدرية المعاوي",
  "phone": "500552192",
  "phone_evening": "",
  "email": "besha@hdc.com.sa",
  "map_url": "https://maps.app.goo.gl/QugRbwMHHphDCnCS8?g_st=ipc",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور  خميس مشيط للرعاية النهارية",
  "region": "عسير",
  "city": "خميس مشيط",
  "address": "فرع خميس مشيط طريق الضيافة – شارع صلاح الدين مقابل قاعة المملكة",
  "manager": "أ.بدرية مرعي سعيد السرحاني",
  "phone": "500051865",
  "phone_evening": "500052543",
  "email": "aseer@hdc.com.sa",
  "map_url": "https://maps.app.goo.gl/TbsdVU9m3H8k9wAG6",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور  أبها للرعاية النهارية",
  "region": "عسير",
  "city": "أبها",
  "address": "ابها - حي الخالدية، - طريق سرد بن عبدالله الازدي،",
  "manager": "أ.نوال القحطاني",
  "phone": "550842755",
  "phone_evening": "",
  "email": "oboor.abha.female@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/xjTtVXsH4UDa9pCu9",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور  جازان للرعاية النهارية",
  "region": "جازان",
  "city": "جازان",
  "address": "جازان  - حي السويس -بشر النصيبي،",
  "manager": "أ.رنيم عمر",
  "phone": "555264409",
  "phone_evening": "555218447",
  "email": "jazan@hdc.com.sa",
  "map_url": "https://maps.app.goo.gl/79ARN1oWmSYNg2Fh9?g_st=ic",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور الإحساء فرع شركة تأهيل الإنسان",
  "region": "الشرقية",
  "city": "الإحساء شركة تأهيل الإنسان",
  "address": "المنطقة الشرقية - محافظة الأحساء - حي العليا - الشارع العام",
  "manager": "أ.مها صالح الطيبان",
  "phone": "500585534",
  "phone_evening": "530464336/534676192",
  "email": "alahsa@hdc.com.sa",
  "map_url": "https://maps.google.com/?q=25.360624,49.590900",
  "lat": 25.360624,
  "lng": 49.5909
 },
 {
  "name": "مركز عبور الإحساء VIP للرعاية النهارية",
  "region": "الشرقية",
  "city": "الإحساء VIP",
  "address": "المنطقة الشرقية - اسماء بنت خارجه،  ، حي محاسن ارامكو الثاني، المبرز",
  "manager": "أ. العنود الرويشد",
  "phone": "573824660",
  "phone_evening": "",
  "email": "",
  "map_url": "https://maps.app.goo.gl/msK8DRkaT2QuSAeKA",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور النعيرية للرعاية النهارية",
  "region": "الشرقية",
  "city": "النعيرية",
  "address": "المنطقة الشرقية - محافظة النعيرية - حي الربيع - شارع ابو جعفر المنصور",
  "manager": "أ.خلود العتيبي",
  "phone": "532862122",
  "phone_evening": "",
  "email": "Nariyah@hdc.com.sa",
  "map_url": "https://maps.app.goo.gl/2JpU2wSrPR6EnESX6?g_st=ipc",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور حفر الباطن للرعاية النهارية",
  "region": "الشرقية",
  "city": "حفر الباطن",
  "address": "المنطقة الشرقية - محافظة حفر الباطن - حي الخالدية - شارع عام",
  "manager": "أ.وفاء مدعث السهلي",
  "phone": "555604098",
  "phone_evening": "",
  "email": "hafarAlBatin@hdc.edu.sa",
  "map_url": "https://maps.google.com/?q=28.423599,45.970692",
  "lat": 28.423599,
  "lng": 45.970692
 },
 {
  "name": "مركز  فرع عبور  الدمام  للرعاية النهارية",
  "region": "الشرقية",
  "city": "الدمام",
  "address": "المنطقة الشرقية - مدينة الدمام - حي النورس - شارع الزهرة",
  "manager": "أ. سجى",
  "phone": "556565599",
  "phone_evening": "",
  "email": "oboor.alkhobar@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/Dqyw2GHDwcjVRrV26?g_st=ic",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور الجبيل للرعاية النهارية",
  "region": "الشرقية",
  "city": "الجبيل",
  "address": "الجبيل ، حي الفناتير",
  "manager": "أ.خلود الطويل",
  "phone": "538301550",
  "phone_evening": "",
  "email": "oboor.aljubail@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/sbXdYBp5BvxSPQcq9?g_st=com.google.maps.preview.copy",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور الخبر للرعاية النهارية",
  "region": "الشرقية",
  "city": "الخبر",
  "address": "الخبر ,العقربية,شارع الشورى",
  "manager": "أ.منال الدوسري",
  "phone": "536412822",
  "phone_evening": "",
  "email": "",
  "map_url": "https://maps.app.goo.gl/aDd7nhhG3WxGLsQk6",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز فرع عبور الطائف  للرعاية النهارية",
  "region": "مكة المكرمة",
  "city": "الطائف",
  "address": "منطقة مكة المكرمة - محافظة الطائف - حي الشرفية - شارع عام",
  "manager": "أ.مثايل الحازمي",
  "phone": "503072539",
  "phone_evening": "",
  "email": "Oboor.altaif@hdc.edu.sa",
  "map_url": "https://goo.gl/maps/iGET6tB1aKbnXt1W8",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز عبور مكة المكرمه للرعاية النهارية",
  "region": "مكة المكرمة",
  "city": "مكة المكرمه",
  "address": "منطقة مكة المكرمة -حي الشوقية",
  "manager": "أ.حنان عبدالله المنبهي",
  "phone": "557288714",
  "phone_evening": "",
  "email": "oboor.makkah@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/A5A7okajDucAxskm7?g_st=ic",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور المدينة المنورة للرعاية النهارية",
  "region": "المدينة المنورة",
  "city": "المدينة المنورة",
  "address": "حي بئر عثمان  - شارع رافع بن جعدبه",
  "manager": "أ.شادية ناير الحربي",
  "phone": "550335136",
  "phone_evening": "",
  "email": "oboor.madinah@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/k8i3EL2T8vVY97Ze6?g_st=ic",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور الجوف للرعاية النهارية",
  "region": "الجوف",
  "city": "الجوف",
  "address": "سكاكا   حي العزيزية، طريق الملك خالد",
  "manager": "أ.ديمة الكويكبي",
  "phone": "557450796",
  "phone_evening": "",
  "email": "oboor.aljouf@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/9SVVHe4Sj9tjzo2B9",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور شباب الإحساء  للرعاية النهارية",
  "region": "الشرقية",
  "city": "الإحساء",
  "address": "أبو الطوق، ، حي الحزم الجنوبي، المبرز",
  "manager": "أ.عمر الخميس",
  "phone": "550839355",
  "phone_evening": "",
  "email": "oboor.alahsa@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/pRXU9og9pboxt56P7?g_st=iw",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور شباب النعيرية  للرعاية النهارية",
  "region": "الشرقية",
  "city": "النعيرية",
  "address": "المنطقة الشرقية - محافظة النعيرية - حي الربيع - شارع ابو جعفر المنصور",
  "manager": "أ.خلود العتيبي",
  "phone": "507857650",
  "phone_evening": "",
  "email": "Nariyah@hdc.com.sa",
  "map_url": "https://maps.app.goo.gl/PCLt642jTCS3L8KG8?g_st=com.google.maps.preview.copy",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور  شباب الدمام  للرعاية النهارية",
  "region": "الشرقية",
  "city": "الدمام",
  "address": "الدمام  -حي بدر - ضياء الدين البشيري",
  "manager": "عمار  بن  مكي",
  "phone": "539813713",
  "phone_evening": "",
  "email": "oboor.aldammam.male@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/vvxLzetaLmtpEZ3FA",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز فرع عبور شباب المجمعة  للرعاية النهارية",
  "region": "الرياض",
  "city": "المجمعة",
  "address": "المجمعة  حي الملك عبدالعزيز، شارع عبيدة بن الحارث",
  "manager": "أ.خالد العصيمي",
  "phone": "550842055",
  "phone_evening": "",
  "email": "oboor.almajmaah@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/D45Led11HaJJbT9i8",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور شباب  الرمال  للرعاية النهارية",
  "region": "الرياض",
  "city": "الرمال",
  "address": "الرياض - حي الرمال",
  "manager": "أ.عادل تركي بن طنف العتيبي",
  "phone": "536793343",
  "phone_evening": "",
  "email": "oboor.alrimal.male@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/ARUGRBVQKxZJ6aBo8?g_st=com.google.maps.preview.copy",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور شباب ابها  للرعاية النهارية",
  "region": "عسير",
  "city": "ابها",
  "address": "طريق سرد بن عبدالله الازدي، ، حي الخالدية،",
  "manager": "أ.محمد العمري",
  "phone": "550819655",
  "phone_evening": "",
  "email": "oboor.abha.male@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/TtfFEJeqGGVPNdZt5",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز عبور شباب خميس مشيط للرعاية النهارية",
  "region": "عسير",
  "city": "خميس مشيط",
  "address": "طريق ابها، خميس مشيط",
  "manager": "أ.فهد فايز الشهري",
  "phone": "558678323",
  "phone_evening": "",
  "email": "oboor.kamis.male@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/p95AzKMezQbNtYDQ6",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور شباب جنوب ابها  للرعاية النهارية",
  "region": "عسير",
  "city": "جنوب ابها",
  "address": "أبها - قرى آل غليظ- بالقرب من طريق مرحباً ألف",
  "manager": "أ.عزام عامر أبوعلام",
  "phone": "573627990",
  "phone_evening": "",
  "email": "oboor.abha.male2@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/m57fkc2fZUjdtV8A7",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع عبور شباب جازان  للرعاية النهارية",
  "region": "جازان",
  "city": "جازان",
  "address": "بشر النصيبي، حي السويس جازان",
  "manager": "أ.تركي بن علي",
  "phone": "538276550",
  "phone_evening": "",
  "email": "oboor.jazan.male@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/79ARN1oWmSYNg2Fh9?g_st=ic",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز  فرع شباب محايل عسير للرعاية النهارية",
  "region": "عسير",
  "city": "محايل عسير",
  "address": "محايل عسير - حي الوعد،",
  "manager": "أ. سعود الغرازي",
  "phone": "538345501",
  "phone_evening": "",
  "email": "oboor.asir.male@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/HwbBtbB6MvZESXG3A",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز   فرع عبور شباب الجوف  للرعاية النهارية",
  "region": "الجوف",
  "city": "الجوف",
  "address": "سكاكا -الربوة",
  "manager": "أ.عبدالعزيز السياط",
  "phone": "534198732",
  "phone_evening": "",
  "email": "oboor.aljouf.male@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/TmuxT18CS4rh7Umf9?g_st=com.google.maps.preview.copy",
  "lat": null,
  "lng": null
 },
 {
  "name": "مركز   فرع عبور شباب العريجاء  للرعاية النهارية",
  "region": "الرياض",
  "city": "العريجاء",
  "address": "الرياض  العريجاء الوسطى، طريق الامير مساعد بن عبدالرحمن بن فيصل،",
  "manager": "أ.راكان عبدالله الضرغام",
  "phone": "551920536",
  "phone_evening": "",
  "email": "oboor.aluraija.male@hdc.edu.sa",
  "map_url": "https://maps.app.goo.gl/j5BbNp299tg1NTYQA",
  "lat": null,
  "lng": null
 }
]""")


class Command(BaseCommand):
    help = "استبدال كل الفروع ببيانات الشركة الرسمية (الفروع الحقيقية)"

    def handle(self, *args, **opts):
        Branch.objects.all().delete()
        for i, b in enumerate(DATA, 1):
            Branch.objects.create(
                slug=f"branch-{i}", order=i,
                name_ar=b["name"], name_en="",
                region_ar=b["region"], city_ar=b["city"], area_ar="",
                address_ar=b["address"], hours_ar="",
                phone=b["phone"], phone_evening=b.get("phone_evening") or "",
                email=b["email"], manager=b["manager"], map_url=b["map_url"],
                lat=b["lat"], lng=b["lng"],
                services_ar=DEFAULT_SERVICES, services_en=[],
                is_new=False, published=True,
            )
        self.stdout.write(self.style.SUCCESS(f"Imported {len(DATA)} branches (replaced all)."))
